import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'
import React from 'react'

const RefundPolicy = () => {
    return (
        <div className="bg-black text-white">
          <Navbar />
          <div className="container mx-auto px-4 py-24">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 py-16 pb-4 text-center">Return & Refund Policy</h1>
            <div className="text-xl text-gray-200 max-w-3xl mx-auto">
              <p>Our Return and Refund Policy was last updated on 5/03/2025.</p>
              <p>Thank you for shopping at Anilyst.</p>
              <p>The following terms are applicable for any products that you have purchased from us.</p>
              <h2 className="text-3xl font-bold mt-8 mb-4">Eligibility for Refunds</h2>
              <p>We offer refunds under the following circumstances:</p>
              <ul className="list-disc pl-5">
                <li>If the service is not delivered as promised due to an error on our end.</li>
                <li>If a technical issue caused by our platform prevents you from accessing the features you paid for, and the issue cannot be resolved within a reasonable timeframe.</li>
                <li>If you cancel your subscription within the refund period outlined below.</li>
              </ul>
              <h2 className="text-3xl font-bold mt-8 mb-4">Refund Period</h2>
              <p>Refund requests must be made within 15 days of the payment date. Requests made after this period will not be eligible for a refund.</p>
              <h2 className="text-3xl font-bold mt-8 mb-4">Non-Refundable Cases</h2>
              <p>Refunds will not be granted under the following conditions:</p>
              <ul className="list-disc pl-5">
                <li>If you change your mind after purchasing a subscription or service.</li>
                <li>If you fail to use the service during the subscription period.</li>
                <li>If the issue is caused by third-party software or tools not affiliated with our platform.</li>
              </ul>
              <h2 className="text-3xl font-bold mt-8 mb-4">Refund Process</h2>
              <p>To request a refund, please follow these steps:</p>
              <ol className="list-decimal pl-5">
                <li>Contact our support team at kaifmohd5000@gmail.com.</li>
                <li>Provide your payment receipt, order ID, and a detailed explanation of the issue.</li>
                <li>Our team will review your request and respond within 3-5 business days.</li>
                <li>If your request is approved, the refund will be processed to your original payment method within 7-10 business days.</li>
              </ol>
              <p>This has been generated by dodopayments.com</p>
              <h2 className="text-3xl font-bold mt-8 mb-4">Contact Us</h2>
              <p>If you have any questions about this Refund Policy or require assistance, please reach out to us:</p>
              <p>Email: kaifmohd5000@gmail.com</p>
            </div>
          </div>
          <Footer />
        </div>
      );
    };
export default RefundPolicy;